language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t charan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true charan/react-test npm run test

after_success:
  - docker build -t charan/multi-client ./client
  - docker build -t charan/multi-nginx ./nginx
  - docker build -t charan/multi-server ./server
  - docker build -t charan/multi-worker ./worker


# login to docker cli

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#take those images and push to docker hub


  - docker push charan/multi-client
  - docker push charan/multi-nginx
  - docker push charan/multi-server
  - docker push charan/multi-worker
  