language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t charanrj/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true charanrj/react-test npm test

after_success:
  - docker build -t charanrj/multi-client ./client
  - docker build -t charanrj/multi-nginx ./nginx
  - docker build -t charanrj/multi-server ./server
  - docker build -t charanrj/multi-worker ./worker


# login to docker cli

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#take those images and push to docker hub


  - docker push charanrj/multi-client
  - docker push charanrj/multi-nginx
  - docker push charanrj/multi-server
  - docker push charanrj/multi-worker
  