language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t charan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true charan/react-test npm run test

after_success:
  - docker build -t charan/multi-client ./client
  - docker build -t charan/multi-nginx ./nginx
  - docker build -t charan/multi-server ./server
  - docker build -t charan/multi-worker ./worker
  